// lib/React/src/pages/index.jsx
/* eslint-disable react/jsx-one-expression-per-line */
/* eslint-disable func-names */
import React from "react";

const Home = function () {
  const [count, setCount] = React.useState(0);

  return (
    <button type="button" onClick={() => setCount(count + 1)}>
      Clicked {count} {count === 1 ? "time" : "times"}
    </button>
  );
};

export default Home;

// lib/Vue/src/pages/index.vue
<template>
  <button @click="handleClick">
    Clicked {{ count }}
    {{ count === 1 ? 'time' : 'times' }}
  </button>
</template>

<script>
export default {
  name: 'home',
  data () {
    return {
      count: 0
    };
  },
  methods: {
    handleClick () {
      this.count++;
    }
  }
}
</script>
